name: Deploy Frontend to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Dev Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /opt/vyuflo-dev/frontend

            git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/VYUSOFT-INC/vyuflo_frontend.git
            git pull origin dev

            cd /opt/vyuflo-dev
            docker compose -f docker-compose.dev.yml up -d --build frontend
